---
- apt: name={{ item }}
  with_items:
    - python-virtualenv
    - openjdk-7-jre-headless
    - git
    - ntp
    - python-crypto
  when: ansible_os_family == 'Debian'
  tags: packages

- yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm" state=present
  when: ansible_os_family == 'RedHat'
- rpm_key: key=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  when: ansible_os_family == 'RedHat'

- yum: name={{ item }}
  with_items:
    - python-virtualenv
    - java-1.7.0-openjdk.x86_64
    - git
    - ntp
    - python-crypto
  when: ansible_os_family == 'RedHat'
